# Generated by Django 3.1.6 on 2021-02-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coins',
            new_name='Coin',
        ),
    ]
