# Generated by Django 3.1.6 on 2021-02-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210214_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
